### ISSUE TITLE
Whut?

### ISSUE THREAD

**Issue by thefonso** [ChrisDowdDeveloper/flashcard#4]
https://github.com/ChrisDowdDeveloper/flashcard/blob/2275f6faa69404d48e5b2e9cd179fcce673ac126/src/components/Home.js#L45

**Comment by ChrisDowdDeveloper** [comment]
https://github.com/ChrisDowdDeveloper/flashcard

here I have removed the functions along with the useHistory(). I thought I
finally understood that the files needed to be loaded and used with Route
into index.js inside of Layout folder with the components and state passed
through it but unfortunately that still isnt working. I understand my
useHistory may not be correct but I was going to try that after creating a
deck so I could test out the delete on a file thats not meant to be in the
JSON file. So for now I am just trying to get my CreateDeck file and my
Home file to link up
